### PR TITLE
Fix tree value not kept when navigating across wizard

### LINKED ISSUE #247: Values in autocomplete tree are cleared when navigated accross wizard
Image

### PR DESCRIPTION
**Pull request by LaChope**
Resolves #247

### CODE REVIEW

**Comment by blcham** [comment]
@LaChope unfortunatelly this is failing ... so what do we do here? Do we commit in main and cherrypick to the PR that we use in record-manager ?

**Comment by LaChope** [comment]
@blcham Sorry I closed this PR in favor of #249 because it was not comparing to correct branch (it was comparing to main when it should have been comparing with downgrade-react-17)

**Comment by LaChope** [comment]
@blcham No, it should be merged to [downgrade-react-17](https://github.com/kbss-cvut/s-forms/tree/downgrade-react-17)

**Comment by blcham** [comment]
> @blcham No, it should be merged to [downgrade-react-17](https://github.com/kbss-cvut/s-forms/tree/downgrade-react-17)

@LaChope, OK i looked to the git history and i see that this was commited on top of [downgrade-react-17](https://github.com/kbss-cvut/s-forms/tree/downgrade-react-17), thus I will use version of alpha package published here directly in record-manager-ui.

**Pull request merged**
