### PR TITLE
Reduced deprecated dependencies

### PR DESCRIPTION
**Pull request by LaChope**
Reduced deprecated dependencies and removed unnecessary ones #108

### CODE REVIEW

**Review by blcham — COMMENTED** [review]
Not sure if you considered warnings in `npm install` command as suggested in #108.

**Comment by LaChope** [comment]
@blcham I do not get such warnings at all with `npm install`, I used the command `npm outdated` and got:

image


Then I used `npm update` and got:

image

**Comment by blcham** [comment]
You are right I don't have issue either, anymore. I get this:
image

**Review by blcham — APPROVED** [review]
LGTM

**Pull request merged**
