### PR TITLE
Added form validation to storybook toolbar

### LINKED ISSUE #311: Validate form from storybook toolbar

### PR DESCRIPTION
**Pull request by LaChope**
Resolves #311.

### CODE REVIEW

**Review by blcham — CHANGES_REQUESTED** [review]
Not sure what it should do. I tried to set value "Validate form"=on or off but it behaved the same.

**Comment by blcham** [comment]
image

**Comment by blcham** [comment]
image

**Comment by LaChope** [comment]
It should not behave like that... It should work the exact same way as in record-manager like the "save" and "complete" buttons

**Comment by blcham** [comment]
So if u navigate to form2 you can immediately see validation errors of all fields?

**Comment by LaChope** [comment]
There is a strange behavior. If I click once, only one part of the form is validated, if I clicked twice, the whole form is validated (see screenshots below):

image

image

**Comment by LaChope** [comment]
This behavior happens only in form2, for instance, it works as expected in aircraft form.

**Comment by blcham** [comment]
Ok give it a couple of minutes to resolve it, if you do not come up with a solution do the merge, i guess it is not that big issue

**Comment by LaChope** [comment]
[b402811](https://github.com/kbss-cvut/s-forms/pull/317/commits/b402811c03365a9d39c80dcaddfd3f77af697b7e) does not fix the issue, but I realized working on this issue that all questions were not traversed by the validator.

I do not know why yet, but "Validate form" must be clicked twice to actually validate. It seems to be linked to storybook rather than validator itself.

**Review by blcham — APPROVED** [review]

**Pull request merged**
