### PR TITLE
Fixed non-selectable values in TypeaheadAnswer

### LINKED ISSUE #231: It is not possible to choose value in select component
It manifests in storybook (did not test it elsewhere)
image

It could happen after migration to react v18.

### PR DESCRIPTION
**Pull request by LaChope**
Resolves #231 and #218.
It seems like [react-select](https://github.com/JedWatson/react-select) does not work well in combination of [react-window](https://github.com/bvaughn/react-window) (see [this issue](https://github.com/JedWatson/react-select/issues/2850)).
Instead [react-windowed-select](https://github.com/jacobworrel/react-windowed-select) is working (see https://github.com/JedWatson/react-select/issues/2850#issuecomment-455750222)

### CODE REVIEW

**Comment by LaChope** [comment]
FYI @VojtechLunak

**Review by blcham — APPROVED** [review]
LGTM

So it solves the issue in typeahead but the same solution cannot be applied to inteligent-tree-component?

**Comment by blcham** [comment]
@LaChope in what state is this ticket?

**Comment by LaChope** [comment]
> @LaChope in what state is this PR?

@blcham it does work in s-forms but not in s-forms-demo...

**Comment by LaChope** [comment]
LGTM

**Pull request merged**
