### PR TITLE
Fix behaviour of irrelevant answerable section in debugMode

### PR DESCRIPTION
**Pull request by LaChope**
It is no longer possible to change value of checkbox for irrelevant question #123

### CODE REVIEW

**Review by blcham — CHANGES_REQUESTED** [review]
I am still able to change the value.

image

**Comment by LaChope** [comment]
> I am still able to change the value.

@blcham Did you refresh the page when you checked-out the page? I cannot reproduce the issue, I cannot change the value anymore

**Comment by blcham** [comment]
@LaChope Yes, I am able to reproduce in Chrome or Firefox.


Steps to reproduce:
- go to the [deployed app with debugMode:true](https://deploy-preview-124--clever-bohr-4e69b7.netlify.app/?path=/story/sforms--tourist-destination-form&globals=debugMode:true) 
- click to the label of disabled "Ma oteviraci dobu"
image

**Review by blcham — APPROVED** [review]
LGTM

**Pull request merged**
