### PR TITLE
[Partial implementation] Steps to implement issue #22

### PR DESCRIPTION
**Pull request by LaChope**

### CODE REVIEW

**Comment by LaChope** [comment]
@blcham I know the layout on the `VerticalWizardNav` is not correct, I will work on it. The issue is that with this react-hotkeys package you must add a component `<HotKeys>` like so:
```
<HotKeys>
    <VerticalWizardNav/>
<HotKeys/>
```
So the render tree is affected

**Comment by blcham** [comment]
> @blcham I know the layout on the `VerticalWizardNav` is not correct, I will work on it. The issue is that with this react-hotkeys package you must add a component `<HotKeys>` like so:
> 
> ```
> <HotKeys>
>     <VerticalWizardNav/>
> <HotKeys/>
> ```
> 
> So the render tree is affected

Sorry, I am not able to follow now. I realized that I made mistake of mixing two features together which complicates the communication. Let's solve this issue first https://github.com/kbss-cvut/s-forms/issues/52.

**Review by blcham — COMMENTED** [review]
This is working strange-ly on following questions:

1. Layout options / Answerable section
1.1. irrelevant attributes are shown ok at page load
image
1.2. [Bug] When I answer "Answerable section", their subquestions should become relevant
Selection_009

2. Conditional logic / Accept state types / Accept answer value / Hidden question
- this question is not shown as "irrelevant question"

**Comment by blcham** [comment]
@LaChope does it makes sense to close and remove the branch ?

**Comment by LaChope** [comment]
Yes, it is not relevant anymore. Resolved with #52

**Pull request closed without merging**
