### PR TITLE
Publish to npm

### PR DESCRIPTION
**Pull request by LaChope**
Added workflows for github action to publish to npm #5

### CODE REVIEW

**Review by blcham — COMMENTED** [review]
- lets talk about it next meeting, comments to discuss:
- not sure why u do not need to generate a specific version i.e. update package.json

TODO:
1) how to publish different beta releases? how will it look like ? ($version-beta-1, ...beta-2 ..)
    - so package.json is automatically changed on server?
2) how do i find out which commit beta release reflects?
3) want to do minor & major release ... how?
    - package.json will be automatically changed? Thus i need to commit after calling npm publish?

**Comment by blcham** [comment]
@LaChope please squash those commits after you are done, so we don't have so much mess in repo

**Comment by blcham** [comment]
@LaChope please squash those commits after you are done, so we don't have so much mess in repo

**Comment by LaChope** [comment]
> @LaChope please squash those commits after you are done, so we don't have so much mess in repo

Yes it is planned :)

**Comment by LaChope** [comment]
Replaced in favor of #136

**Pull request closed without merging**
